/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}",
  ],
  safelist: [
    // evitar purge de classes geradas dinamicamente
    "bg-ys-amber", "text-ys-amber", "from-ys-bg/60", "to-ys-bg",
  ],
  theme: {
    container: { center: true, padding: '1rem' },
    extend: {
      fontFamily: { sans: 'var(--f-sans)' },
      colors: {
        brand: {
          DEFAULT: 'var(--c-brand-500)',
          50: 'var(--c-brand-50)',
          100: 'var(--c-brand-100)',
          200: 'var(--c-brand-200)',
          300: 'var(--c-brand-300)',
          400: 'var(--c-brand-400)',
          500: 'var(--c-brand-500)',
          600: 'var(--c-brand-600)',
          700: 'var(--c-brand-700)',
          800: 'var(--c-brand-800)',
          900: 'var(--c-brand-900)',
        },
        bg: 'var(--c-bg)',
        surface: 'var(--c-surface)',
        surface2: 'var(--c-surface-2)',
        border: 'var(--c-border)',
        borderStrong: 'var(--c-border-strong)',
        text: 'var(--c-text)',
        textSoft: 'var(--c-text-soft)',
        muted: 'var(--c-muted)',
        success: 'var(--c-success)',
        warning: 'var(--c-warning)',
        danger: 'var(--c-danger)',
        info: 'var(--c-info)',
        prova: 'var(--c-prova)',
        trabalho: 'var(--c-trabalho)',
        projeto: 'var(--c-projeto)',
        teste: 'var(--c-teste)',
        outros: 'var(--c-outros)',
        conteudo: 'var(--c-conteudo)',
        data: 'var(--c-data)',
        'ys-amber': 'var(--c-brand-500)',
        'ys-bg': 'var(--c-bg)',
        'ys-card': 'var(--c-surface)',
        'ys-ink': 'var(--c-text)',
        'ys-ink-2': 'var(--c-text-soft)',
        'ys-ink-3': 'var(--c-muted)',
        'ys-line': 'var(--c-border)',
        ys: { orange1: 'var(--c-brand-300)', orange2: 'var(--c-brand-400)' },
      },
      borderRadius: {
        xs: 'var(--r-xs)',
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
        '2xl': 'var(--r-2xl)',
        '3xl': 'var(--r-3xl)',
      },
      boxShadow: {
        soft: 'var(--sh-soft)',
        card: 'var(--sh-card)',
        elev: 'var(--sh-elev)',
      },
      transitionDuration: {
        fast: 'var(--dur-fast)',
        mid: 'var(--dur-mid)',
        slow: 'var(--dur-slow)',
      },
      backgroundImage: {
        'brand-grad': 'linear-gradient(135deg,var(--g-brand-from),var(--g-brand-to))',
      },
    },
  },
  plugins: [],
}
