services:
  - type: web
    name: site-professor-yago-api
    env: node
    rootDir: api
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # Deixe isso como false para definir manualmente no Render
      - key: JWT_SECRET
        sync: false # Deixe isso como false para definir manualmente no Render
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
  
  - type: web
    name: site-professor-yago-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://site-professor-yago-api.onrender.com
