name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      # se você tem workspaces, instale o que precisar por workspace:
      - name: Install frontend deps
        run: npm --workspace frontend ci

      - name: Install backend deps
        run: npm --prefix backend ci

      - name: Backend tests
        run: npm --prefix backend test --if-present

      - name: Frontend build
        run: npm --workspace frontend run build --if-present
