name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SMTP: ${{ secrets.SMTP }}
      APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
      MONGOMS_VERSION: 8.12.2
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install backend dependencies
        run: npm install --prefix backend
      - name: Install frontend dependencies
        run: npm install --prefix frontend
      - name: Clean MongoDB cache
        run: rm -rf ~/.cache/mongodb-binaries
      - run: npm test --prefix backend
      - run: npm test --prefix frontend
      - name: Build project
        run: npm run build --prefix frontend
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist
      - name: Deploy frontend
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend
      - name: Deploy backend
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
