name: Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install backend dependencies
        run: npm install --prefix backend
      - name: Install frontend dependencies
        run: npm install --prefix frontend
      - run: npm test --prefix backend
      - run: npm test --prefix frontend
      - name: Build project
        run: npm run build --prefix frontend
      - name: Deploy
        run: echo "Deploying artifacts to the hosting service"
        # TODO: Add deployment commands
