name: Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SMTP: ${{ secrets.SMTP }}
      APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install backend dependencies
        run: npm install --prefix backend
      - name: Install frontend dependencies
        run: npm install --prefix frontend
      - run: npm test --prefix backend
      - run: npm test --prefix frontend
      - name: Build project
        run: npm run build --prefix frontend
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist
      - name: Deploy
        run: echo "Deploying artifacts to the hosting service"
        # TODO: Add deployment commands
